DROP TABLE IF EXISTS REQUEST;
DROP TABLE IF EXISTS PRODUCED;
DROP TABLE IF EXISTS ARTIST;
DROP TABLE IF EXISTS CONTRIBUTION;
DROP TABLE IF EXISTS SINGER;
DROP TABLE IF EXISTS KARAOKEFILE;
DROP TABLE IF EXISTS SONG;

CREATE TABLE SONG(
    TRACKNUM INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(256)
);

CREATE TABLE KARAOKEFILE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    VERSION VARCHAR(64),
    LYRICS VARCHAR(256),
    TRACKNUM INT,
    FOREIGN KEY(TRACKNUM) REFERENCES SONG(TRACKNUM)
);

CREATE TABLE SINGER(
    STAGENAME VARCHAR(256) PRIMARY KEY
);

CREATE TABLE CONTRIBUTION(
    CONTRIBUTION VARCHAR(256),
    CONTRIBUTOR VARCHAR(256),
    PRIMARY KEY(CONTRIBUTION, CONTRIBUTOR)
);

CREATE TABLE ARTIST(
    NAME VARCHAR(256) PRIMARY KEY
);

CREATE TABLE PRODUCED(
    TRACKNUM INT,
    NAME VARCHAR(256),
    CONTRIBUTION VARCHAR(256),
    PRIMARY KEY(TRACKNUM, NAME, CONTRIBUTION),
    FOREIGN KEY(TRACKNUM) REFERENCES SONG(TRACKNUM),
    FOREIGN KEY(NAME) REFERENCES ARTIST(NAME),
    FOREIGN KEY(CONTRIBUTION) REFERENCES CONTRIBUTION(CONTRIBUTION)
);

CREATE TABLE REQUEST(
    QUEUENUM INT UNIQUE AUTO_INCREMENT,
    ISPAID BOOLEAN,
    TRACKNUM INT,
    STAGENAME VARCHAR(256),
    PRIMARY KEY(TRACKNUM, STAGENAME, QUEUENUM),
    FOREIGN KEY(TRACKNUM) REFERENCES SONG(TRACKNUM),
    FOREIGN KEY(STAGENAME) REFERENCES SINGER(STAGENAME)
);